name: Azure Pipelines

trigger:
  branches:
    include:
      - main

pool:
  name: myAgentPool

variables:
  - group: azure-credentials   
  - group: azure-storage-key
  - group: vm-ssh-key          
  - name: python_version
    value: '3.8.10'
  - name: azureServiceConnectionId
    value: 'ServiceConnex'
  - name: projectRoot
    value: '$(System.DefaultWorkingDirectory)'
  - name: environmentName
    value: 'test'
  - name: vmImageName
    value: 'devopsVM'

stages:
- stage: Build
  displayName: 'Provision Infrastructure'
  jobs:
    - job: BuildInfrastructure
      displayName: 'Infrastructure Provisioning'
      steps:
        - task: Bash@3
          displayName: 'Write SSH Public Key to id_rsa.pub'
          inputs:
            targetType: 'inline'
            script: |
              echo "$ADMIN_SSH_PUBLIC_KEY" > "$(projectRoot)/terraform/environments/test/id_rsa.pub"
              chmod 644 "$(projectRoot)/terraform/environments/test/id_rsa.pub"

        - task: ArchiveFiles@2
          displayName: 'Archive FakeRestAPI'
          inputs:
            rootFolderOrFile: '$(projectRoot)/automatedtesting/jmeter/fakerestapi'
            includeRootFolder: false
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'

        - task: PublishBuildArtifacts@1
          displayName: 'Upload Package'
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'
            ArtifactName: 'drop-fakerestapi'
            publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  jobs:
    - deployment: FakeRestAPI
      displayName: 'Deploy to Azure App Service'
      environment: 'test'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadPipelineArtifact@2
                displayName: 'Download Build Artifact'
                inputs:
                  artifact: 'drop-fakerestapi'
                  path: '$(Pipeline.Workspace)'

              - task: AzureWebApp@1
                displayName: 'Deploy to Azure Web App'
                inputs:
                  azureSubscription: 'ServiceConnex'
                  appName: 'myWebApp-AppService-59f507ec'
                  appType: 'webApp'
                  package: '$(Pipeline.Workspace)/drop-fakerestapi/$(Build.BuildId)-fakerestapi.zip'
